### ISSUE TITLE
default shell runner registration is skipped

### ISSUE THREAD

**Issue by opichon** [debops/ansible-gitlab_runner#11]
```
TASK [debops.gitlab_runner : Check if GitLab service is available] ******************************************************************************************************************************
ok: [scw-0783ca]

TASK [debops.gitlab_runner : Register new GitLab Runners] ***************************************************************************************************************************************
skipping: [scw-0783ca] => (item={u'name': u'scw-0783ca', u'executor': u'shell'})
```
My playbook uses the gitlab_runner role straight out of the box, with little cofiguration except to provide the Gitlab CI token.

**Comment by drybjed** [comment]
It seems to be a bit [complex condition](https://github.com/debops/ansible-gitlab_runner/blob/master/tasks/main.yml#L95-L100), you could start by checking the state of the `gitlab_runner__register_api` and `gitlab_runner__token` variables using the `debug` Ansible module. Also, can you show the Ansible facts file the role produces?

**Comment by opichon** [comment]
Thanks for your reply. My configuration was wrong, and it now works fine. Sorry to have troubled you.
