### ISSUE TITLE
Support GitLab 10

### ISSUE THREAD

**Issue by dacrome** [debops/ansible-gitlab_runner#16]
Hi,

first of all thanks for this great ansible role.

Currently this role uses api version v1 to manage runners, but in GitLab 10 this api version is not supported anymore. Current version is v4: https://docs.gitlab.com/ce/api/runners.html

Is there any plan to update to this version?

Greetz,
David

**Comment by drybjed** [comment]
Sure, I'll try to add support for v4 before merging GitLab 10 support. Thanks for the heads up.

**Comment by drybjed** [comment]
@dacrome Any idea where I can find documentation about adding Runners via v4 API? [This page doesn't seem to have this described](https://docs.gitlab.com/ce/api/runners.html), did the procedure change significantly?

**Comment by dacrome** [comment]
Hi @drybjed 

thanks for the fast feedback.

I think the register global/shared runner API is not documented, but I registered a runner via
POST `/api/v4/runners`. I just changed `Register new GitLab Runners` step :)

I found the API in this merge request: https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9246/diffs#099c283e57e8f3941e27a043e2ad347c368c1d3c

API Changes
- The path changes from `/ci/api/` to `/api`
- `/runners/register.json` does not existing anymore

Greetz,
David

**Comment by dacrome** [comment]
maybe it is easier to use the non-interactive registration command?
https://docs.gitlab.com/runner/commands/README.html#non-interactive-registration

**Comment by drybjed** [comment]
Oh, I actually have v4 support already working, thanks. Just need to clean the changes up a bit and update documentation. It should be merged this week at most.

I'll probably also rearrange the role to be executed late in the playbook, so that it can detect most of the configured stuff and correctly generate tags for things like OpenVZ/KVM/LXC/Docker. That way recreating the hosts should be easy.

**Comment by drybjed** [comment]
This should be now fixed in the latest release.

**Comment by dacrome** [comment]
Thanks @drybjed !

I already tried it. the registration works like a charm.
But the deletion is only working on the runner machine, but not in GitLab.
The deletion task is always skipped:
```
TASK [debops.gitlab_runner : Delete GitLab Runners if requested] *******************************************************************************************************************
skipping: [my-runner] => (item=(censored due to no_log)) 
```

**Comment by drybjed** [comment]
For the removal to work, you need to set the `gitlab_runner__api_token` to your access token, found on your GitLab profile page; actually you will need to generate a new one since existing tokens are not displayed.

**Comment by dacrome** [comment]
works like a charm :)
thanks again!
